// React/src/pages/Contact.js
import React, { useState } from 'react';
import axios from 'axios';

const Contact = () => {
  const [formData, setFormData] = useState({ name: '', email: '', message: '' });

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await axios.post('http://localhost:5000/contacts', formData);
      alert('Form submitted successfully!');
      setFormData({ name: '', email: '', message: '' }); // Reset form after submission
    } catch (error) {
      console.error('Error submitting form:', error);
    }
  };

  return (
    <div className="container mt-5">
      <h1>Contact Me</h1>
      <form onSubmit={handleSubmit} className="mt-3">
        <div className="mb-3">
          <label>Name</label>
          <input type="text" className="form-control" name="name" value={formData.name} onChange={handleChange} required />
        </div>
        <div className="mb-3">
          <label>Email</label>
          <input type="email" className="form-control" name="email" value={formData.email} onChange={handleChange} required />
        </div>
        <div className="mb-3">
          <label>Message</label>
          <textarea className="form-control" name="message" value={formData.message} onChange={handleChange} required />
        </div>
        <button type="submit" className="btn btn-primary">Send</button>
      </form>
    </div>
  );
};

export default Contact;

// Anuglar/src/app/pages/contact/contact.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  standalone: false,
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css'
})
export class ContactComponent {
  name: string = '';
  email: string = '';
  message: string = '';
  successMessage: string = '';
  errorMessage: string = '';

  constructor(private http: HttpClient) {}

  submitForm() {
    if (!this.name || !this.email || !this.message) {
      this.errorMessage = "All fields are required!";
      setTimeout(() => this.errorMessage = '', 3000);
      return;
    }

    const formData = { name: this.name, email: this.email, message: this.message };

    this.http.post('http://localhost:4500/contacts', formData).subscribe({
      next: () => {
        this.successMessage = "Message sent successfully!";
        this.name = '';
        this.email = '';
        this.message = '';
        setTimeout(() => this.successMessage = '', 3000);
      },
      error: () => {
        this.errorMessage = "Failed to send message.";
        setTimeout(() => this.errorMessage = '', 3000);
      }
    });
  }
}
<div class="contact-container">
    <div class="contact-card">
      <h2>Contact Me</h2>
      <p>I'd love to hear from you! Feel free to reach out.</p>
  
      <form (submit)="submitForm()">
        <!-- Name Input -->
        <div class="input-group">
          <input type="text" id="name" [(ngModel)]="name" name="name" required />
          <label for="name">Your Name</label>
        </div>
  
        <!-- Email Input -->
        <div class="input-group">
          <input type="email" id="email" [(ngModel)]="email" name="email" required />
          <label for="email">Your Email</label>
        </div>
  
        <!-- Message Input -->
        <div class="input-group">
          <textarea id="message" rows="4" [(ngModel)]="message" name="message" required></textarea>
          <label for="message">Your Message</label>
        </div>
  
        <!-- Success & Error Messages -->
        <div *ngIf="successMessage" class="alert alert-success">
          {{ successMessage }}
        </div>
        <div *ngIf="errorMessage" class="alert alert-danger">
          {{ errorMessage }}
        </div>
  
        <!-- Submit Button -->
        <button type="submit" class="send-btn">Send Message</button>
      </form>
    </div>
  </div>
